#================================================================================
# Standard configuration
#================================================================================

baseURL                = "https://um-grex.github.io/grex-dev/"
copyright              = "The MIT License (MIT) Copyright © 2022 um-grex"

defaultContentLanguage = "en"
enableEmoji            = false
enableGitInfo          = true
metaDataFormat         = "yaml"

publishDir             = "public"
title                  = "Unofficial Grex User Guide"

theme                  = "shadocs"
#themesdir              = "../.."

[Author]
  name = "Ali Kerrache, Grigory Shamov"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.71.0'
    max = ''
  [[module.mounts]]
    source = 'openapi'
    target = 'static/openapi'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = false

[Languages]
  [Languages.en]
    contentDir   = "content/english"
    title        = "Grex"
    weight       = 1
    languageName = "English"

  #[Languages.fr]
    #contentDir   = "content/french"
    #title        = "Grex"
    #weight       = 2
    #languageName = "Français"

#================================================================================
# Miscellaneous sidebar parameters
#================================================================================

[sidebar]
  homeSectionIconDefault = "fa-solid fa-house-chimney"
  firstSectionIconDefault = "fa-solid fa-ban"
  nestedSectionIconDefault = "fa-solid fa-turn-up fa-rotate-90 fa-xs"

#================================================================================
# Specific configuration
#================================================================================

[params]
  logo               = "logo/um_logo_email_signature.png"
  logoTouch          = "logo/um_logo_email_signature.png"
  image404           = "images/404.gif"
  favicon            = "images/grex-favicon.png"
  faviconmd          = "![](images/grex-favicon.png)"
  homeLayout         = "onboarding"
  siteContentOrder   = "weight"
  globalBanner       = false
  currentVersion     = "latest"
  latestVersionUrl   = "http://um-grex.github.io/grex-docs/"
  [params.navbar.shortcuts]
    [params.navbar.shortcuts.example]
       keys     = ["Shift","1"]
       function = "scExample"
    [[params.navbar.versions]]
       name = 'Production version'
       url  = 'https://um-grex.github.io/grex-dev/'
    [[params.navbar.versions]]
       name = 'Development version'
       url  = 'http://um-grex.github.io/grex-docs/'
    [[params.navbar.versions]]
       name = 'Deprecated version'
       url  = 'http://um-grex.github.io/grex-docs/'
  [params.taxonomies]
    [params.taxonomies.categories]
       icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
       icon = "fa-solid fa-tag"
  [params.includes]
     jsModules = [
         "js/shortcuts.js"
     ]
     js        = []
     css       = [
         "css/shortcuts.css"
     ]
  [params.versions]
    hugo_min         = "[0.71.0](https://github.com/gohugoio/hugo/releases/tag/v0.71.0)"
    bulma            = "[0.9.3](https://github.com/jgthms/bulma/releases/tag/0.9.3)"
    fontawesome      = "[5.15.4](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.15.4)"
    overlayscrollbar = "[1.13.1](https://github.com/KingSora/OverlayScrollbars/releases/tag/1.13.1)"
    flexsearch       = "[0.7.2](https://github.com/nextapps-de/flexsearch/releases/tag/0.7.2)"
    mermaid          = "[8.13.4](https://github.com/mermaid-js/mermaid/releases/tag/8.13.4)"
    qrious           = "[4.0.2](https://github.com/neocotic/qrious/releases/tag/4.0.2)"
    intro            = "[4.3.0](https://github.com/usablica/intro.js/releases/tag/v4.3.0)"
    swaggerui        = "[4.1.0](https://github.com/swagger-api/swagger-ui/releases/tag/v4.1.0)"

#================================================================================
# GitHub links displayed in the information modal
#================================================================================

[github]
  main = "https://um-grex.github.io/grex-dev"
  download = "https://um-grex.github.io/archive/main.zip"
  issue = "https://um-grex.github.io/issues"
  fork = "https://um-grex.github.io/fork"

#================================================================================
# End of the config file.
#================================================================================
